# Generated by CTkMaker, cleaned + wired to app logic

import customtkinter as ctk


class MainWindow(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title("IDUNA")
        self.geometry("900x600")
        self._build_ui()
        self.entry_1.bind("<Return>", self.on_unlock)

    def _build_ui(self):
        self.label_3 = ctk.CTkLabel(
            self,
            width=567,
            height=44,
            corner_radius=0,
            border_width=0,
            border_color='#565b5e',
            fg_color='transparent',
            text='Welcome to the S@FE',
            justify='center',
            text_color='#ffffff',
            text_color_disabled='#a0a0a0',
            compound='left',
            font=ctk.CTkFont(size=50, weight="normal"),
        )
        self.label_3.place(x=175, y=20)

        self.entry_1 = ctk.CTkEntry(
            self,
            show="*",
            width=462,
            height=31,
            corner_radius=6,
            border_width=2,
            border_color='#565b5e',
            placeholder_text='(e.g. masterPassword)',
            fg_color='#343638',
            text_color='#dce4ee',
            placeholder_text_color='#9ea0a2',
            justify='left',
            font=ctk.CTkFont(size=13, weight="normal"),
        )
        self.entry_1.place(x=219, y=285)

        self.label_4 = ctk.CTkLabel(
            self,
            width=216,
            corner_radius=0,
            border_width=0,
            border_color='#565b5e',
            fg_color='transparent',
            text='Enter master password',
            justify='center',
            text_color='#ffffff',
            text_color_disabled='#a0a0a0',
            compound='left',
            font=ctk.CTkFont(size=18, weight="normal"),
        )
        self.label_4.place(x=228, y=250)

        self.label_5 = ctk.CTkLabel(
            self,
            width=323,
            height=20,
            corner_radius=0,
            border_width=0,
            border_color='#565b5e',
            fg_color='transparent',
            text='Be very sure u can remember the master password',
            anchor='nw',
            justify='left',
            text_color='#8d8d8d',
            text_color_disabled='#a0a0a0',
            compound='left',
            font=ctk.CTkFont(size=13, weight="bold", slant="italic"),
        )
        self.label_5.place(x=10, y=580)

    def on_unlock(self, event=None):
        master_password = self.entry_1.get()
        print("Captured:", master_password)  # temporary — confirms binding works
        # next steps once this is confirmed working:
        # 1. from src.db import init_db; init_db()
        # 2. store master_password somewhere accessible to the rest of the app
        # 3. destroy this window, open the main entries window


if __name__ == "__main__":
    ctk.set_appearance_mode("dark")
    app = MainWindow()
    app.mainloop()